apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity-apiserver
  namespace: kube-system
  labels:
    run: identity-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: identity-apiserver
  template:
    metadata:
      labels:
        run: identity-apiserver
    spec:
      serviceAccountName: identity-apiserver
      containers:
      - image: gcr.io/mikedanese-k8s/identity-apiserver
        name: identity-apiserver
        imagePullPolicy: Always
        volumeMounts:
        - name: tmpdir
          mountPath: /tmp
      volumes:
      - name: tmpdir
        emptyDir: {}
