kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: idmgr
  namespace: kube-system
  labels:
    app: idmgr
spec:
  template:
    metadata:
      labels:
        app: idmgr
    spec:
      containers:
        - name: idmgr
          image: gcr.io/mikedanese-k8s/idmgr:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: poddir
            mountPath: /var/lib/kubelet/pods
          - name: tmpdir
            mountPath: /tmp
          - name: driver
            mountPath: /volumeplugin/k8s.io~identity
      volumes:
        - name: poddir
          hostPath:
            path: /var/lib/kubelet/pods
        - name: tmpdir
          hostPath:
            path: /tmp
        - name: driver
          hostPath:
            path: /tmp/volumeplugin/k8s.io~identity
