apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
spec:
  nodeName: k-4-minion-group-7mbb
  containers:
  - name: tester
    command: ["sleep", "100000"]
    image: ubuntu
    imagePullPolicy: Always
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "k8s.io/identity"
