apiVersion: v1
kind: Pod
metadata:
  name: idcli
  namespace: default
spec:
  nodeName: k-4-minion-group-7mbb
  containers:
  - name: idcli
    command: ["sleep", "100000"]
    image: gcr.io/mikedanese-k8s/idcli
    imagePullPolicy: Always
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "k8s.io/identity"
