load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["copy.go"],
    importpath = "k8s.io/identity/pkg/util",
    visibility = ["//visibility:public"],
)
