// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/apis/idmgr/idmgr.proto

/*
Package pkg_api is a generated protocol buffer package.

It is generated from these files:
	pkg/apis/idmgr/idmgr.proto

It has these top-level messages:
	CreateIdentityVolumeRequest
	CreateIdentityVolumeResponse
	DestroyIdentityVolumeRequest
	DestroyIdentityVolumeResponse
*/
package pkg_api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateIdentityVolumeRequest struct {
	MountPath      string            `protobuf:"bytes,1,opt,name=mount_path,json=mountPath" json:"mount_path,omitempty"`
	ServiceAccount string            `protobuf:"bytes,2,opt,name=service_account,json=serviceAccount" json:"service_account,omitempty"`
	MountOptions   map[string]string `protobuf:"bytes,3,rep,name=mount_options,json=mountOptions" json:"mount_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CreateIdentityVolumeRequest) Reset()                    { *m = CreateIdentityVolumeRequest{} }
func (m *CreateIdentityVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateIdentityVolumeRequest) ProtoMessage()               {}
func (*CreateIdentityVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateIdentityVolumeRequest) GetMountPath() string {
	if m != nil {
		return m.MountPath
	}
	return ""
}

func (m *CreateIdentityVolumeRequest) GetServiceAccount() string {
	if m != nil {
		return m.ServiceAccount
	}
	return ""
}

func (m *CreateIdentityVolumeRequest) GetMountOptions() map[string]string {
	if m != nil {
		return m.MountOptions
	}
	return nil
}

type CreateIdentityVolumeResponse struct {
}

func (m *CreateIdentityVolumeResponse) Reset()                    { *m = CreateIdentityVolumeResponse{} }
func (m *CreateIdentityVolumeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateIdentityVolumeResponse) ProtoMessage()               {}
func (*CreateIdentityVolumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DestroyIdentityVolumeRequest struct {
	MountPath string `protobuf:"bytes,1,opt,name=mount_path,json=mountPath" json:"mount_path,omitempty"`
}

func (m *DestroyIdentityVolumeRequest) Reset()                    { *m = DestroyIdentityVolumeRequest{} }
func (m *DestroyIdentityVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*DestroyIdentityVolumeRequest) ProtoMessage()               {}
func (*DestroyIdentityVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DestroyIdentityVolumeRequest) GetMountPath() string {
	if m != nil {
		return m.MountPath
	}
	return ""
}

type DestroyIdentityVolumeResponse struct {
}

func (m *DestroyIdentityVolumeResponse) Reset()                    { *m = DestroyIdentityVolumeResponse{} }
func (m *DestroyIdentityVolumeResponse) String() string            { return proto.CompactTextString(m) }
func (*DestroyIdentityVolumeResponse) ProtoMessage()               {}
func (*DestroyIdentityVolumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CreateIdentityVolumeRequest)(nil), "pkg.api.CreateIdentityVolumeRequest")
	proto.RegisterType((*CreateIdentityVolumeResponse)(nil), "pkg.api.CreateIdentityVolumeResponse")
	proto.RegisterType((*DestroyIdentityVolumeRequest)(nil), "pkg.api.DestroyIdentityVolumeRequest")
	proto.RegisterType((*DestroyIdentityVolumeResponse)(nil), "pkg.api.DestroyIdentityVolumeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Management service

type ManagementClient interface {
	CreateIdentityVolume(ctx context.Context, in *CreateIdentityVolumeRequest, opts ...grpc.CallOption) (*CreateIdentityVolumeResponse, error)
	DestroyIdentityVolume(ctx context.Context, in *DestroyIdentityVolumeRequest, opts ...grpc.CallOption) (*DestroyIdentityVolumeResponse, error)
}

type managementClient struct {
	cc *grpc.ClientConn
}

func NewManagementClient(cc *grpc.ClientConn) ManagementClient {
	return &managementClient{cc}
}

func (c *managementClient) CreateIdentityVolume(ctx context.Context, in *CreateIdentityVolumeRequest, opts ...grpc.CallOption) (*CreateIdentityVolumeResponse, error) {
	out := new(CreateIdentityVolumeResponse)
	err := grpc.Invoke(ctx, "/pkg.api.Management/CreateIdentityVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementClient) DestroyIdentityVolume(ctx context.Context, in *DestroyIdentityVolumeRequest, opts ...grpc.CallOption) (*DestroyIdentityVolumeResponse, error) {
	out := new(DestroyIdentityVolumeResponse)
	err := grpc.Invoke(ctx, "/pkg.api.Management/DestroyIdentityVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Management service

type ManagementServer interface {
	CreateIdentityVolume(context.Context, *CreateIdentityVolumeRequest) (*CreateIdentityVolumeResponse, error)
	DestroyIdentityVolume(context.Context, *DestroyIdentityVolumeRequest) (*DestroyIdentityVolumeResponse, error)
}

func RegisterManagementServer(s *grpc.Server, srv ManagementServer) {
	s.RegisterService(&_Management_serviceDesc, srv)
}

func _Management_CreateIdentityVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIdentityVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServer).CreateIdentityVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkg.api.Management/CreateIdentityVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServer).CreateIdentityVolume(ctx, req.(*CreateIdentityVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Management_DestroyIdentityVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyIdentityVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServer).DestroyIdentityVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pkg.api.Management/DestroyIdentityVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServer).DestroyIdentityVolume(ctx, req.(*DestroyIdentityVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Management_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pkg.api.Management",
	HandlerType: (*ManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIdentityVolume",
			Handler:    _Management_CreateIdentityVolume_Handler,
		},
		{
			MethodName: "DestroyIdentityVolume",
			Handler:    _Management_DestroyIdentityVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apis/idmgr/idmgr.proto",
}

func init() { proto.RegisterFile("pkg/apis/idmgr/idmgr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xdd, 0x16, 0x95, 0x8e, 0xff, 0x43, 0x85, 0xb2, 0xb6, 0x5a, 0x16, 0xff, 0xf4, 0xb4,
	0x85, 0x0a, 0x22, 0x82, 0x88, 0xa8, 0x07, 0x0f, 0x45, 0xe9, 0xc1, 0x8b, 0x87, 0x12, 0xdb, 0x61,
	0x1b, 0xda, 0x4d, 0x62, 0x32, 0x5b, 0xd8, 0xb3, 0x9f, 0xd3, 0xef, 0x22, 0xdd, 0xac, 0x28, 0xb8,
	0xb6, 0xe2, 0x25, 0x24, 0x8f, 0x37, 0x6f, 0x7e, 0x33, 0x04, 0x7c, 0x3d, 0x8e, 0xda, 0x5c, 0x0b,
	0xdb, 0x16, 0xc3, 0x38, 0x32, 0xee, 0x0c, 0xb5, 0x51, 0xa4, 0xd8, 0xaa, 0x1e, 0x47, 0x21, 0xd7,
	0x22, 0x78, 0x2b, 0xc1, 0xde, 0x8d, 0x41, 0x4e, 0x78, 0x3f, 0x44, 0x49, 0x82, 0xd2, 0x27, 0x35,
	0x49, 0x62, 0xec, 0xe1, 0x6b, 0x82, 0x96, 0x58, 0x03, 0x20, 0x56, 0x89, 0xa4, 0xbe, 0xe6, 0x34,
	0xaa, 0x79, 0x4d, 0xaf, 0x55, 0xe9, 0x55, 0x32, 0xe5, 0x91, 0xd3, 0x88, 0x9d, 0xc0, 0x96, 0x45,
	0x33, 0x15, 0x03, 0xec, 0xf3, 0xc1, 0x60, 0x26, 0xd7, 0x4a, 0x99, 0x67, 0x33, 0x97, 0xaf, 0x9d,
	0xca, 0x9e, 0x61, 0xc3, 0xe5, 0x28, 0x4d, 0x42, 0x49, 0x5b, 0x2b, 0x37, 0xcb, 0xad, 0xb5, 0xce,
	0x59, 0x98, 0x83, 0x84, 0x73, 0x20, 0xc2, 0xee, 0xac, 0xf2, 0xc1, 0x15, 0xde, 0x49, 0x32, 0x69,
	0x6f, 0x3d, 0xfe, 0x26, 0xf9, 0x57, 0xb0, 0xf3, 0xc3, 0xc2, 0xb6, 0xa1, 0x3c, 0xc6, 0x34, 0x47,
	0x9e, 0x5d, 0x59, 0x15, 0x96, 0xa7, 0x7c, 0x92, 0x60, 0x8e, 0xe8, 0x1e, 0x17, 0xa5, 0x73, 0x2f,
	0xd8, 0x87, 0x7a, 0x71, 0x7f, 0xab, 0x95, 0xb4, 0x18, 0x5c, 0x42, 0xfd, 0x16, 0x2d, 0x19, 0x95,
	0xfe, 0x67, 0x4b, 0xc1, 0x01, 0x34, 0x7e, 0x29, 0x77, 0xf9, 0x9d, 0x77, 0x0f, 0xa0, 0xcb, 0x25,
	0x8f, 0x30, 0x46, 0x49, 0x0c, 0xa1, 0x5a, 0x84, 0xc3, 0x0e, 0xff, 0xb2, 0x2d, 0xff, 0x68, 0x81,
	0x2b, 0x9f, 0x69, 0x89, 0x8d, 0x60, 0xb7, 0x10, 0x8b, 0x7d, 0x25, 0xcc, 0x9b, 0xda, 0x3f, 0x5e,
	0x64, 0xfb, 0xec, 0xf4, 0xb2, 0x92, 0xfd, 0xba, 0xd3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x87,
	0x38, 0xca, 0x63, 0x93, 0x02, 0x00, 0x00,
}
